Repository OSWeekends/agenda, pull requests merged in 2020-10, with the labels that each got.

#57 Add design images
  design/desktop.png
  design/mobile.png
Labels: enhancement

#60 New design including speakers' avatar
  design/Mobile.png
  design/desktop.png
  design/mobile.png
Labels: design, enhancement, hacktoberfest-accepted

#61 New header section
  src/components/BaseHeader.vue
  src/components/CustomBadge.vue
  src/data/index.js
  src/views/Home.vue
Labels: design, enhancement, hacktoberfest-accepted

#69 New design images
  design/Mobile.png
  design/desktop.png
Labels: new-design

#70 Feat/time line#68
  src/App.vue
  src/components/ScheduleTable.vue
Labels: design, enhancement, new-design

#75 Twitch/Location Link
  src/main.js
  src/views/Home.vue
Labels: enhancement, new-design

#76 https y # añadidos
  README.md
  src/router.js
Labels: bug, hacktoberfest-accepted

#97 New style of CustomBadge
  src/components/CustomBadge.vue
  src/data/index.js
Labels: design, enhancement, hacktoberfest-accepted, new-design

#102 fix font size and margin of title
  src/components/BaseHeader.vue
Labels: enhancement, new-design
